### ISSUE TITLE
Accept initial query in the URL

### ISSUE THREAD

**Issue by cohan** [spatie/dnsrecords.io#15]
Feature request that would make this slot nicely into my workflow would be if the first query could be provided in the URL, for example if I went to https://dnsrecords.io/example.com it would print the results for example.com straight away when the page loads. 

This way you could add dnsrecords.io as a custom browser search engine (I use the keyword dig) using "https://dnsrecords.io/%s" and in the address bar you can then use "dig example.com" (or more frequently "dig ip") to speedily access the result

Having the request directly under the base isn't a requirement for this, it would happily work as "https://dnsrecords.io/?q=%s" for example

**Comment by cwhite92** [comment]
Second this. Happy to submit a PR if this would be accepted.

**Comment by freekmurze** [comment]
I’d accept a PR for this.

**Comment by freekmurze** [comment]
Will be added soon via #17
