### ISSUE TITLE
404 is thrown if URL with scheme is defined in URL

### ISSUE THREAD

**Issue by svenluijten** [spatie/dnsrecords.io#21]
Go to https://dnsrecords.io/https://spatie.be. This'll throw a 404 because there's a `/` in the URL after the domain name. This can be fixed by adding `->where('command', '\S+');` after [this line](https://github.com/spatie/dnsrecords.io/blob/master/routes/web.php#L4).

**Comment by freekmurze** [comment]
We'll handle this in #23
