### ISSUE TITLE
Full URLs redirect to that URL

### ISSUE THREAD

**Issue by svenluijten** [spatie/dnsrecords.io#22]
## Example
- Go to https://dnsrecords.io
- Copy & paste `https://spatie.be` into the "terminal"
- Hit enter
- You're redirected to https://spatie.be

## Why
This happens because of [this line](https://github.com/spatie/dnsrecords.io/blob/master/resources/assets/js/app.js#L7), which sets the form's `action` attribute to whatever was written in the input.

## Solution
Ideally, when the user enters a full URL, it'll parse the input and post to whatever it was without the scheme (`https://`, `ftp://`), in the example's case just `spatie.be`.

**Comment by freekmurze** [comment]
We'll handle it further in #24
