### ISSUE TITLE
URLs with protocols might need some filtering

### ISSUE THREAD

**Issue by willemvb** [spatie/dnsrecords.io#27]
https://github.com/spatie/dnsrecords.io/blob/master/resources/assets/js/app.js#L7-L10 

Only filtering the protocol on the front end is not enough.
Eg. you can visit —without the URL being corrected

- https://dnsrecords.io/http://spatie.be
- https://dnsrecords.io///
- https://dnsrecords.io///http://spatie.be

Subsequent entries in the search field keeps the weird pattern. Eg. enter `spatie.com` after last example and you get `https://dnsrecords.io///http://spatie.com` as url.

**Comment by freekmurze** [comment]
Fixed in #33
