### ISSUE TITLE
403 blade view

### ISSUE THREAD

**Issue by willemvb** [spatie/dnsrecords.io#31]
`https://dnsrecords.io/...` gives a 403. 

I've made a Blade template but it doesn't get picked up like other errors.

(BTW not sure why `https://dnsrecords.io/..` kinda works and `https://dnsrecords.io/...` not)

**Comment by freekmurze** [comment]
Seems like nginx is tripping on `...` This problem occurs on many different sites as well. Let's just filter out `...` client side for now.

**Comment by brendt** [comment]
@freekmurze I think a better approach would be to handle that error in the new middleware I added in #33, server side. Though `...` might be the one exception which doesn't even reach Laravel's router.

If it's possible, are you ok with filtering it out serverside?

**Comment by freekmurze** [comment]
Merged #33

**Comment by brendt** [comment]
@freekmurze unfortunately, I believe this URL never reaches Laravel's router: `dnsrecords.io/...`.

One part of the solution is the filter `...` uit client side, but the URL itself would still be shareable. I think the only way to really fix it, is to rewrite `...` in nginx.

**Comment by freekmurze** [comment]
Seems a problem across a lot of forge provisioned sites. I'm going to leave it as it is for now.
