### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: The Mix manifest does not exist. 

### ISSUE THREAD

**Issue by Vudubond** [spatie/dnsrecords.io#38]
Hello,

Im getting:

PHP Fatal error:  Uncaught Exception: The Mix manifest does not exist. in /home/user/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:567
Stack trace:
#0 /home/user/public_html/storage/framework/views/b755704e7f40b2c669c847c7c10e0584f915ee4f.php(13): mix('/css/app.css')
#1 /home/user/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include('/home/user/pu...')
#2 /home/user/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/user/pu...', Array)
#3 /home/user/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/home/user/pu...', Array)
#4 /home/user/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#5 /home/user/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#6 /home/user/pu in /home/user/public_html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 567

**Comment by freekmurze** [comment]
You probably forgot to compile the assets.

Run `yarn run dev` to compile.

Keep in mind that we that give support on the code in this repo. If you want to use it, just point your browser to https://dnsrecords.io/
