### ISSUE TITLE
Convert unicode letters to punycode

### ISSUE THREAD

**Issue by manniL** [spatie/dnsrecords.io#39]
A few minutes ago I wanted to look up the DNS settings for "ms-umzüge.de", which contains a German umlaut (öäü). Unfortunately, those are stripped out since #9 came through. It'd not suffice to just accept them because `dig` wouldn't find the Unicode domain. You would also need to convert the domain to Punycode. 

(Same would apply to Chinese letters)

**Comment by freekmurze** [comment]
Feel free to submit a PR to fix this.

**Comment by crock** [comment]
I'll try to fix this.

**Comment by mattiasgeniar** [comment]
Some pointers having [implemented this myself](https://dnsspy.io/);

# Explicit character sets

When calling `dig` you'll want to explicitly set the Character Set via `CHARSET=ASCII`. Ie:
```
CHARSET=ASCII dig +nocmd ... 
```

This'll require some love in [Dns.php](https://github.com/spatie/dns/blob/master/src/Dns.php#L97).

# Conversions

Before & after each DNS lookup, you'll want to throw in some [idn_to_ascii()](http://php.net/manual/en/function.idn-to-ascii.php) & [idn_to_utf8()](http://php.net/manual/en/function.idn-to-utf8.php).

- translate 'täst.de' to 'xn--tst-qla.de': [idn_to_ascii()](http://php.net/manual/en/function.idn-to-ascii.php)
- translate 'xn--tst-qla.de' to 'täst.de': [idn_to_utf8()](http://php.net/manual/en/function.idn-to-utf8.php)

Once you tell `dig` to use the ASCII charset, you feed it only ascii chars. The response will also be ascii, so you have to convert that back to IDN for the human readable version.

**Comment by crock** [comment]
I'm a little confused. Is any changes supposed to be made in this repo or just in https://github.com/spatie/dns because `Dns.php` is in the other repo.

**Comment by freekmurze** [comment]
@mattiasgeniar thanks for your wisdom here!

@crock dnsrecords.io uses spatie/dns under the hood. So send your PR to spatie/dns.
