### ISSUE TITLE
Empty input throws 500

### ISSUE THREAD

**Issue by manniL** [spatie/dnsrecords.io#40]
When not typing anything into the input field and submitting the request, the 500 error page is shown.

![image](https://user-images.githubusercontent.com/640208/41788670-b63573da-764c-11e8-955e-65978ee0cd11.png)

Instead there should be a simple error message (similar to when requesting an invalid domain )

**Comment by brendt** [comment]
Thanks for reporting, it's fixed!

**Comment by manniL** [comment]
Great :+1: 

But is it intended that there is just a "page reload" and no error message or hint for the user now? :thinking:
