### ISSUE TITLE
Copy last result to clipboard

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/dnsrecords.io#49]
I'm not sure how yet. Been thinking about this, but not happy with any interface. 

- A "copy" button somewhere. After the result? A global button?
- Via a command? To be in line with unix, it'd need to be something like `pbcopy | spatie.be`, but that's quite verbose. Maybe just a `copy` command?

Any ideas?

**Comment by freekmurze** [comment]
Though `pbcopy` is correct in the context of a terminal, `copy` is probably a bit more friendly to type.

Maybe just add a command `copy` to copy the result currently displayed. 

Could you make cmd+A make select only the result text? Then people could just cmd+A cmd+C.

**Comment by freekmurze** [comment]
Love de prefilled question idea!
