### ISSUE TITLE
Precedent input when typing ↑

### ISSUE THREAD

**Issue by rchoffardet** [spatie/dnsrecords.io#5]
It would be really great if the site behaved like a terminal (and it would fit with the current design). That's why it would be nice if the site were to go back to recent history when you press the "↑" key.

**Comment by bbashy** [comment]
I tried that hoping someone had done some amazing magic!

**Comment by sebastiandedeyne** [comment]
Might be cool to keep this in local storage 🤔

**Comment by rchoffardet** [comment]
@sebastiandedeyne : Originally, I thought it would be done in a basic array variable. But your idea is so much better!

**Comment by rchoffardet** [comment]
The only "complicated" point I see is the strange behavior of modifying Shell history:

When you modify an element of the history, it remains modified until you execute the modified command. Then, the change is discarded. BUT, all the others changes still remain.

**Comment by freekmurze** [comment]
We'll handle this further in #13
